<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
const PENDING = 'pending'; // 等待
const FULFILLED = 'fulfilled'; // 成功
const REJECTED = 'rejected'; // 失败
class MyPromise {
    constructor(executor) {
        // 加入try、catch 如果执行器中出现错误就调用reject更改状态
        try {
            // 执行传入的函数参数
            executor(this.resolve, this.reject)
        } catch (e) {
            this.reject(e);
        }
    }
    // Promise状态
    status = PENDING;
    // 成功之后的值
    value = undefined;
    // 失败之后的原因
    reason = undefined;
    // 成功回调
    successCallback = [];
    // 失败回调
    failCallback = [];

    // 更改为成功状态
    resolve = value => {
        // 如果不是等待状态 就阻止程序向下执行
        if (this.status !== PENDING) return;
        this.status = FULFILLED;
        // 保存成功之后的值
        this.value = value;
        // 判断成功回调是否存在 如果存在则调用
        // this.successCallback && this.successCallback(this.value);

        // 以数组的长度作为条件，将前面的回调函数弹出并调用 shift()方法的返回值就是我们需要的函数
        // 每当执行一次数组就会删除一个，数组长度为零时就不再执行
        while (this.successCallback.length) this.successCallback.shift()()
    }
    // 更改为失败状态
    reject = reason => {
        // 如果不是等待状态 就阻止程序向下执行
        if (this.status !== PENDING) return;
        this.status = REJECTED;
        // 保存失败后的原因
        this.reason = reason;
        // 判断失败回调是否存在 如果存在则调用
        // this.failCallback && this.failCallback(this.reason);
        // 以数组的长度作为条件，将前面的回调函数弹出并调用 shift()方法的返回值就是我们需要的函数
        // 每当执行一次数组就会删除一个，数组长度为零时就不再执行
        while (this.failCallback.length) this.failCallback.shift()()
    }
    then(successCallback, failCallback) {
        // 创建一个新的promise对象 并返回
        let promise2 = new MyPromise((resolve, reject) => {
            // 判断状态
            if (this.status === FULFILLED) {
                // 由于resolvePromise 中的promise2在new Mypromise没有执行完之前是拿不到的，所以这里我们要加入setTimeout改为异步代码
                setTimeout(() => {
                    // 加入try、catch 如果执行器中出现错误就调用reject更改状态
                    try {
                        // 将回调的结果传给下一个then方法
                        const x = successCallback(this.value);
                        // 判断x的值是普通值还是promise对象，如果是普通值，直接调用resolve
                        // 如果是promise对象，查看promise对象返回的结果，根据结果决定调用resolve还是reject
                        resolvePromise(promise2, x, resolve, reject);
                    } catch (e) {
                        // 调用下一个promise的reject方法
                        reject(e);
                    }
                }, 0)
            } else {
                // 等待状态 
                // 将成功回调和失败回调保存起来
                this.successCallback.push(() => {
                    // 将回调的结果传给下一个then方法
                    const x = successCallback(this.value);
                    // 判断x的值是普通值还是promise对象，如果是普通值，直接调用resolve
                    // 如果是promise对象，查看promise对象返回的结果，根据结果决定调用resolve还是reject
                    resolvePromise(promise2, x, resolve, reject);
                });
            }
        });
        return promise2
    }
    finally(callback) {
        // 调用then方法拿到当前promise的状态
        return this.then(value => {
            // 调用MyPromise.resolve处理callback()返回的结果，并返回
            return MyPromise.resolve(callback()).then(() => value)
        }, reason => {
            return MyPromise.resolve(callback()).then(() => { throw reason })
        })
    }
    catch (failCallback) {
        return this.then(undefined, failCallback)
    }
}
const resolvePromise = (promise2, x, resolve, reject) => {
    if (promise2 === x) {
        // 自己返回自己 返回reject
        reject(new TypeError('Chaining cycle detected for promise #<Promise>'))
    }
    if (x instanceof MyPromise) {
        // 是promise对象
        // x.then(value => { resolve(value) }, reason => { reject(reason) }) 相当于 x.then(resolve,reject)
        x.then(resolve, reject)
    } else {
        // 是普通值 直接返回
        resolve(x)

    }
}
        
        let p = new MyPromise(function(resolve, reject){
            resolve(111)
        })
        p.then(function(result){
            console.log(result)
            return 222
        }).then(function(result){
            console.log(result)
            return 333
        }).then(function(result){
            console.log(result)
        })
    </script>
</body>
</html>